### ISSUE TITLE
Failed to load

### ISSUE THREAD

**Issue by 64er** [holxsam/tldraw-in-obsidian#1]
I cloned the repository as described to <vault path>/.obsidian/plugins/, but when I tried to enable it, I got “Failed to load plugin” on obsidian mobile.

**Comment by NarrowWoodBridge** [comment]
When you clone, you just get the source code instead of the plugin compiled, please download from the Releases and put the files under the subfolder of the plugin folder.

**Comment by holxsam** [comment]
As NarrowWoodBridge has said, if you cloned the repo you then just have the source code not the files you need for the plugin. You can generate the files from the source code but running `npm run build` but that is most likely not an option if you're using Obsidian on mobile. There are more detailed instructions in the [README.md](https://github.com/holxsam/tldraw-in-obsidian/blob/main/README.md). I recommend installing using the "easy way" which uses BRAT (another community plugin). Let me know if you still have issues!
