### ISSUE TITLE
Issues with Dark Mode Persistence and Importing from tldraw.com in tldraw 

### ISSUE THREAD

**Issue by mikedeanlive** [holxsam/tldraw-in-obsidian#10]
# Issues with Dark Mode Persistence and Importing from tldraw.com in tldraw Extension

## Hello tldraw-in-obsidian Team,

I want to express my appreciation for your work on the tldraw extension. It's a fantastic tool. However, I've encountered a couple of issues that I'd like to bring to your attention:

### 1. Dark Mode Setting Not Persisting

**Issue Description:**
- Every time I reopen the extension, it defaults back to light mode, even though I had set it to dark mode in the previous session.

**Expected Behavior:**
- It would be great if the dark mode setting could persist across sessions, saving the need to change it every time I reopen the extension.

### 2. Challenges with Importing from tldraw.com

**Issue Description:**
- Currently, I am unable to paste content directly from the standard tldraw.com website into the tldraw extension. Also, there seems to be no option to upload files directly into the extension.

**Expected Behavior:**
- Having the ability to paste or import content from tldraw.com directly into the extension would greatly enhance its usability and streamline the workflow.

I hope these issues can be addressed in future updates. Thank you again for your hard work and dedication to this project.

**Comment by holxsam** [comment]
> ### 1. Dark Mode Setting Not Persisting
> **Issue Description:**
> 
> * Every time I reopen the extension, it defaults back to light mode, even though I had set it to dark mode in the previous session.
> 
> **Expected Behavior:**
> 
> * It would be great if the dark mode setting could persist across sessions, saving the need to change it every time I reopen the extension.

I think what's happening is you're changing the theme by going menu > preferences > dark mode which is definitely a bug I have to look into but as a temporary fix you go into your Obsidian settings > Tldraw > Theme > Change it to your preference, it should persist.

> ### 2. Challenges with Importing from tldraw.com
> **Issue Description:**
> 
> * Currently, I am unable to paste content directly from the standard tldraw.com website into the tldraw extension. Also, there seems to be no option to upload files directly into the extension.
> 
> **Expected Behavior:**
> 
> * Having the ability to paste or import content from tldraw.com directly into the extension would greatly enhance its usability and streamline the workflow.

This is something I hadn't thought of that I really like the idea of so I'll try my best to implement it but no promises because I've been a bit short on time :(

**Comment by mikedeanlive** [comment]
I can add a little bounty (in crypto) if this gets implemented (tldr import and copy pasta). 
What do you think?

**Comment by jon-dez** [comment]
@mikedeanlive Copy and paste works now as expected in this release https://github.com/jon-dez/tldraw-in-obsidian/releases/tag/update-to-tldraw-2.4.4--2

**Comment by jon-dez** [comment]
Support for importing files has now been released: https://github.com/holxsam/tldraw-in-obsidian/releases/tag/1.4.0
