### ISSUE TITLE
Command to embed into current document

### ISSUE THREAD

**Issue by Reun85** [holxsam/tldraw-in-obsidian#17]
When inside a file add a command to:
create a new TlDraw document, while placing a link at the current cursor position.
If possible name the TlDraw document using the current file's name.

**Comment by Bosmut** [comment]
Yeah, seems like a perfect option. I was looking for a plugin with such functionality to embed it is obsidian, but no luck so far.

**Comment by jon-dez** [comment]
@Reun85 @Bosmut 

I've made a pull request that implements, this feature. See more info here https://github.com/holxsam/tldraw-in-obsidian/pull/22#issuecomment-2154213634
