### ISSUE TITLE
Can't copy and past tldraw-web ↔ tldraw-obsidian

### ISSUE THREAD

**Issue by kevinhojae** [holxsam/tldraw-in-obsidian#18]
Currently, the tldraw-obsidian plugin does not allow sharing whiteboard with others, so I need to migrate tldraw-web content to my personal tldraw-obsidian area. 

However, when I copy and paste the content from tldraw-web into tldraw-obsidian, there is no content pasted into the obsidian whiteboard area.
Nor I can't copy content from tldraw-obsidian to tldraw-web for the same reason.

Is there any way to copy and paste from one to the other or is this an issue that will be resolved once the obsidian plugin is updated?

**Comment by jessmartin** [comment]
> Is there any way to copy and paste from one to the other or is this an issue that will be resolved once the obsidian plugin is updated?

This should be resolved once the plugin is updated to the most recent version of TLDraw, currently `2.0.2`. This plugin is currently running `2.0.0-alpha.14`, and there's a breaking schema change between `alpha.14` and `2.0.2` that prevents copy-paste between the two.

I'm maintaining a TLDraw plugin embedded in a different app and I ran into this same problem.
