### ISSUE TITLE
Please don't use online fonts - Download them once

### ISSUE THREAD

**Issue by Hugo-COLLIN** [holxsam/tldraw-in-obsidian#19]
I use a program that isolates my Obsidian vault from the internet, so **when I open a TLDraw drawing I get the error "Could not load assets, please refresh the page"**. 

When I saw TLdraw trying to download online fonts, I created a new Obsidian vault on another device (with no internet restrictions), downloaded TLdraw and used it a bit. **I thought fonts would be downloaded in `.obsidian/plugins/tldraw` but there is only `main.js`, `manifest.json` and `styles.css` files.**

**It seems TLdraw send HTTP requests to use the fonts each time you open a drawing**. So I can't use TLdraw on my main vault.

**Could you please download the fonts a single time and then use the local font files**? (Even an option in settings to choose to use the fonts locally)

![image](https://github.com/holxsam/tldraw-in-obsidian/assets/101000595/a12cd080-ee89-4215-9db0-3ad7390b862e)

![image](https://github.com/holxsam/tldraw-in-obsidian/assets/101000595/aebef04f-4703-494c-b166-af7c6f304590)

**Comment by frangio** [comment]
It looks like this is the code that's necessary to fix this: https://github.com/tldraw/tldraw/blob/9ba4f7cf2a25039df26aff0f8988e78e7b19e0d0/apps/examples/src/examples/static-assets/StaticAssetsExample.tsx

**Comment by jon-dez** [comment]
@Hugo-COLLIN see #31

**Comment by jon-dez** [comment]
Marking this as closed, see #33 and https://github.com/holxsam/tldraw-in-obsidian/releases/tag/1.1.0
