### ISSUE TITLE
Add settings option to allow maintaining current tool selection after tool use.

### ISSUE THREAD

**Issue by N-Argyle** [holxsam/tldraw-in-obsidian#20]
If you draw a shape, after drawing that shape the selected tool resets to your default tool (pointer, hand, etc). This can be frustrating if you intend to draw multiples of the same shape. E.g. drawing multiple lines in a row. You have to reselect the tool each time. Expected behavior for many similar apps is to leave the tool selected, rather than resetting after drawing. 

Haven't looked at how tldraw is integrated, but if you want, I am happy to fork and make a PR for this if it's viable.

**Comment by Bosmut** [comment]
Yeah, great idea! had the same today, while was using this addon

**Comment by jon-dez** [comment]
@N-Argyle If you are still interested in making a PR, I would happily review it.

**Comment by jon-dez** [comment]
I figured out that there is a default keybind for this. Basically select the shape you want to keep using, and press `q` on your keyboard. You can also click the lock button when you have your shape selected.

![image](https://github.com/user-attachments/assets/6b88e88d-48c2-47c9-b536-360e51d97846)
