### ISSUE TITLE
Ability to export a .tldr file

### ISSUE THREAD

**Issue by cdierkens** [holxsam/tldraw-in-obsidian#27]
## Description

tldr.com has the option to "Save a Copy" and "Open a file". Both of these operate on the `.tldr` extension.

<img width="308" alt="image" src="https://github.com/user-attachments/assets/e41da84a-9c26-4603-908b-1291c6fd8d81">

## Request

Implement the ability to export a `.tldr` from Obsidian.

## Related

This is the inverse of #11

**Comment by jon-dez** [comment]
I can confirm this works as intended.
