### ISSUE TITLE
Zoom to fit on embeds

### ISSUE THREAD

**Issue by volkyeth** [holxsam/tldraw-in-obsidian#28]
Currently, the embeds preview seems to always render a section from the origin coordinate (0,0), so the drawing will most likely not be completely visible in the preview.

I propose making the embeds apply a "zoom to fit" so the drawings are always completely visible.

**Comment by jon-dez** [comment]
Just to clarify for anyone who may have time to implement this, does the zoom to fit here work well for you?
![image](https://github.com/user-attachments/assets/cd2c8796-24c9-4c4b-8e07-8b24336a8876)

I wonder if we can instruct tldraw to "call" that same function or position the tldraw viewport just how that button does when you click it, but when the embed loads and only when in preview mode.

**Comment by jon-dez** [comment]
@volkyeth I've implemented this and created a release [here](https://github.com/jon-dez/tldraw-in-obsidian/releases/tag/issue-28) (install instructions included) if you want to test it.

Side note: it also includes the changes from @cdierkens's PR #26, which allows saving to a .tldr file.

**Comment by jon-dez** [comment]
Marking this as closed, see https://github.com/holxsam/tldraw-in-obsidian/releases/tag/1.1.0
