### ISSUE TITLE
Opportunity to change the font

### ISSUE THREAD

**Issue by DaudUzbek2005** [holxsam/tldraw-in-obsidian#29]
Please, I beg you, give me the opportunity to change the font. at least just on some Inter. Your plugin is just perfect, but the font ruins everything

**Comment by jon-dez** [comment]
As a style option that could be set per component, or to override the default fonts?

**Comment by jon-dez** [comment]
@DaudUzbek2005 see #31

**Comment by jon-dez** [comment]
Marking this as closed, see https://github.com/holxsam/tldraw-in-obsidian/releases/tag/1.1.0
