### ISSUE TITLE
Inline drawing in Markdown file

### ISSUE THREAD

**Issue by damien122** [holxsam/tldraw-in-obsidian#3]
Hi, is it possible to create such a drawing and embed it into a markdown note?

**Comment by holxsam** [comment]
Not yet, I'm working on this atm.

**Comment by jon-dez** [comment]
I've made a pull request that implements, this feature. See more info here https://github.com/holxsam/tldraw-in-obsidian/pull/22#issuecomment-2154213634

**Comment by fugohan** [comment]
@jon-dez, I saw your pull request and it looks great! I was wondering if you could add the feature to automatically export to PNG/JPG with the addition for light and darkmode? Excalidraw also has implemented this feature, so it'd be great if you could do the same!

**Comment by jon-dez** [comment]
@fugohan, If you don't mind creating a new issue detailing the specifics of the feature I will take a look at it when I have free time. Also include some screenshots and/or a screen recording if applicable.

**Comment by holxsam** [comment]
Merged jon's PR and released the update: https://github.com/holxsam/tldraw-in-obsidian/releases/tag/1.0.6
