### ISSUE TITLE
Right Click BUG

### ISSUE THREAD

**Issue by Medullitus** [holxsam/tldraw-in-obsidian#32]
When you click right click it opens new tab. There is NO option to disable it. I had to disable the plugin bec of that.. Can you fix that plz? Thx..

**Comment by jon-dez** [comment]
Right click where? Can you be more specific or provide screenshots?

**Comment by mteam88** [comment]
Experiencing the same issue, whenever the plugin is enabled a right click within a file will open a new tab.

**Comment by Medullitus** [comment]
Hello @jon-dez and @mteam88 ,

Thank you for your responses.

When I right-click anywhere on the screen, it opens a new tab. It's not possible to show this with a screenshot. I think you can test this on your own Obsidian while the plugin is active.

Thank you for the great plugin, and I wish you success in developing it further. But unfortunately, I have to disable the plugin until the issue is fixed.

**Comment by jon-dez** [comment]
This issue doesn't exist for me, so unfortunately I cannot diagnose the bug. Can you test this plugin in a new vault with no other community plugins installed? Also, which version do you have installed?

**Comment by Medullitus** [comment]
Hello,

I hope you are doing well. It seems that the issue has somehow been resolved for now. So, I’m marking the topic as resolved. If the issue reoccurs, I will write here again. Thank you for your attention.
