### ISSUE TITLE
Date Format Issue

### ISSUE THREAD

**Issue by Medullitus** [holxsam/tldraw-in-obsidian#34]
Hello,

When I set the date format to "DD-MM-YYYY HH:mm" I cannot create a new "tldrawing" file. Could you please help? Thank you...

**Comment by jon-dez** [comment]
Tested this and saw an error in the developer console:

```
app.js:1 Uncaught (in promise) Error: File name cannot contain any of the following characters: \ / :
    at Cb (app.js:1:723786)
    at t.checkPath (app.js:1:731028)
    at t.<anonymous> (app.js:1:732913)
    at app.js:1:237138
    at Object.next (app.js:1:237243)
    at app.js:1:236159
    at new Promise (<anonymous>)
    at v (app.js:1:235904)
    at t.create (app.js:1:732801)
    at TldrawPluginDevelopment.createFile (plugin:tldraw:94890:33)
```
Searched around an found it is a limitation in obsidian

See https://forum.obsidian.md/t/valid-characters-for-file-names/55307/2

So for now I guess avoid using characters that obsidian deems as invalid. I wasn't given a warning about it when changing the setting, so I think there should be a way to prevent users from entering those characters.

**Comment by jon-dez** [comment]
Closing due to software limitations
