### ISSUE TITLE
Where to save attachments

### ISSUE THREAD

**Issue by balta2ar** [holxsam/tldraw-in-obsidian#35]
Hi! I'm absolutely thrilled to see a new active contributor here, @jon-dez, thank you for the recent release and all the updates! :heart: 

I was wondering if it could be possible to save attachments in the folder relative to the currently edited file when embedding a new drawing. For example, Excalidraw has this setting:

![image](https://github.com/user-attachments/assets/eeb9a5e6-ead8-4c66-80ee-2959e36a18b5)

and then in "Files and links" settings I have:

![image](https://github.com/user-attachments/assets/e6a5656c-f992-4a02-bf76-04f78a5713d7)

and this combination makes it possible to save new drawings in the ./attach folder relative to the current file when I create a new embedded drawing.

**Comment by jon-dez** [comment]
@balta2ar could you test this [release](https://github.com/jon-dez/tldraw-in-obsidian/releases/tag/1.1.1%2Bissue-35) please?
