### ISSUE TITLE
Minimalistic preview when embedding

### ISSUE THREAD

**Issue by balta2ar** [holxsam/tldraw-in-obsidian#36]
It would be great if it was possible to make previews of embedded diagrams a little more minimalistic, disable any controls so that I don't change anything accidentally when I'm in "viewing" mode. The use-case for that is when I have a note that contains a mixture of text, images, and several diagrams. If I need to edit a diagram, I open it, but most of the time when I'm reading the document, I only need to look at a diagram, not interact with it.

For an example, consider how Excalidraw displays diagrams when in preview:

![image](https://github.com/user-attachments/assets/6ee3023a-e38f-4241-8b97-5688e23375ae)

And draw.io:

![image](https://github.com/user-attachments/assets/ca63929a-1f07-4e5e-9a2d-b91cd48a3667)

For draw.io, I use this fork: https://github.com/mvdkwast/drawio-obsidian

**Comment by jon-dez** [comment]
So currently the markdown embed view uses tldraw's read-only mode, which allows for interacting with the diagram but without modifying it. If I understand correctly you are asking to change that interactive view with a static prerendered view (e.g. jpeg, png), preferably set by default?

**Comment by balta2ar** [comment]
oh I didn't realize it was read-only mode where I can't change anything! :open_mouth:  but you got me 100% correct: hiding any controls / UI elements would be helpful in embedded mode to avoid distractions :slightly_smiling_face:

**Comment by tramy12062017** [comment]
Sorry if I posted in the wrong place. I am newbie on Github. I like your plugin. It is even a bit nice than Excalidraw. Pls keep up your work and update regularly. I have a recommend feature that have on Excalidraw, the line and arrow tool can draw waves as below image. It will perfect if your team finish that
![Screenshot 08-19-2024 17 02 50](https://github.com/user-attachments/assets/f779c110-1f2c-4701-bb04-602b79e567c5)

**Comment by jon-dez** [comment]
@tramy12062017 No problem! New issues are created in the [issues](https://github.com/holxsam/tldraw-in-obsidian/issues) tab. 

![image](https://github.com/user-attachments/assets/c3418564-59df-4068-93d9-c742a112e557)

Then click the green button "New issue".

Would you mind reposting your comment above as two separate issues so that more people can see it and hopefully provided feedback? Thanks

**Comment by tramy12062017** [comment]
@jon-dez I already did it

**Comment by jon-dez** [comment]
@balta2ar Feature implemented in this preview: https://github.com/jon-dez/tldraw-in-obsidian/releases/tag/1.3.0-preview.1

**Comment by balta2ar** [comment]
@jon-dez thank you! There is definitely fewer UI components now! It looks like the tldraw canvas is still reacting to mouse events, e.g. some elements get highlighted ("first" is blue on the picture) and it is possible to scroll the tldraw's view by mistake.
![image](https://github.com/user-attachments/assets/b0711247-3c54-45dd-84bc-3484dc750ed6)
On top of that I was also wondering if it could be possible to hide even the Edit button and the filename to make it even more minimalistic. Editing could be started either by clicking on the diagram (Excalidraw) or by having an Edit option in the context menu (draw.io).
What do you think?

**Comment by jon-dez** [comment]
@balta2ar The unintentional scrolling behavior and the automatic selection will be fixed in the next release. I am working on making the file name and associated buttons visible only when the diagram is "focused", i.e. by clicking on the diagram. When I finish up with that I will create a new release.

**Comment by jon-dez** [comment]
https://github.com/holxsam/tldraw-in-obsidian/releases/tag/1.3.0
