### ISSUE TITLE
cannot open or create sketches on ipad after update to latest tldraw

### ISSUE THREAD

**Issue by rdthree** [holxsam/tldraw-in-obsidian#37]
**Bug Report: Issue with Sketches on iPad**

**Description:**
The application on my iPad has stopped functioning correctly when interacting with sketches.

**Steps to Reproduce:**
1. Open the application on an iPad.
2. Attempt to open an existing sketch. 
   - Result: An error message appears stating "failed to open."
3. Attempt to create a new sketch, either by clicking the button or using the command panel.
   - Result: No action occurs; the sketch does not get created.

**Additional Information:**
- If I create a new sketch on my desktop, I am able to open it on my iPad without issues.
- This problem appears to be isolated to creating and opening sketches directly on the iPad.

**Device/OS Information:**
- Device: iPad

**Comment by jon-dez** [comment]
@rdthree can you install this pre-release and confirm the issue is fixed here https://github.com/jon-dez/tldraw-in-obsidian/releases/tag/1.1.0%2Bissue-37

**Comment by rdthree** [comment]
Yes! It works again. Thanks for the one plugin that really allows sketching and hand writing on iPad!On Aug 15, 2024, at 9:40 PM, Jonathan Mendez ***@***.***> wrote:﻿
@rdthree can you install this pre-release and confirm the issue is fixed here https://github.com/jon-dez/tldraw-in-obsidian/releases/tag/1.1.0%2Bissue-37
