### ISSUE TITLE
Please don't use online icons - Download them once

### ISSUE THREAD

**Issue by Hugo-COLLIN** [holxsam/tldraw-in-obsidian#44]
This issue is the continuation of #19.

For a reminder, my vault is isolated from the internet. So, I downloaded and specified custom fonts to avoid TLdraw loading error.

Now, I can access and draw with the TLdraw interface, but I cannot see any icon as they are all loaded from the internet.

A simple way to solve this problem would be to provide an icon set you can download and then select it from the plugin settings page.

Here is a capture of what it looks like:
![image](https://github.com/user-attachments/assets/9a431517-d047-48af-9f3f-6fac7d833b8c)

**Comment by jon-dez** [comment]
@Hugo-COLLIN I'm curious, how did you manage to isolate your vault from the internet?

**Comment by jon-dez** [comment]
https://github.com/jon-dez/tldraw-in-obsidian/releases/tag/1.5.0-preview.2
@Hugo-COLLIN Could you see if this works for you? You should be able to override individual icons, as well as select a folder from within your vault to read icons from. One caveat for the folder selection, icons in the folder must match the icon names that tldraw use. For more information, see the settings page or return to me with questions.

**Comment by Hugo-COLLIN** [comment]
> @Hugo-COLLIN I'm curious, how did you manage to isolate your vault from the internet?

I use Plucky (also called Pluckeye - https://pluckyfilter.com). It mainly allows you to block your access to certain websites, but you can also use it to prevent applications from making network requests.

**Comment by jon-dez** [comment]
Oh ok, I was just wondering. Also, fyi the release I posted above is out of date. The most recent is post as a release on this repo.

**Comment by Hugo-COLLIN** [comment]
@jon-dez I tried your preview version and it works fine for me! (Edit: I'll try the release)

When I opened issue #19, my concern was also about regular Obsidian users : why do we need to request assets from the internet each time ? Downloading fonts and icons a single time in `.obsidian/plugins/tldraw` would avoid repetitive network requests for something you can get once at first launch of TLdraw-for-obsidian.

**Comment by jon-dez** [comment]
@Hugo-COLLIN That is a valid point. I think that is something that could be implemented in the future.

**Comment by Hugo-COLLIN** [comment]
Assets overrides seems not working when embedding Tldraw drawing in a regular note (blocked at fonts), I'll open a new issue.
