### ISSUE TITLE
[Bug]: Image stored in Base64 exceeds file limit

### ISSUE THREAD

**Issue by 0PandaDEV** [holxsam/tldraw-in-obsidian#46]
I was using the Obsidian plugin of tldraw. While trying to add a image the entire canvas crashed because the image was added in base64 it exceeded the character limit on Obsidian which meant I lost my entire progress.

**Comment by jon-dez** [comment]
I'm sorry to hear that this happened. You might be able to restore the file if it exists in the file recovery tab in Obsidian.

![image](https://github.com/user-attachments/assets/7b45bb95-66d2-49aa-8070-2d9d6985da7e)
![image](https://github.com/user-attachments/assets/c09a87c9-1f6a-481d-91d4-fd6d5d8db3b0)
![image](https://github.com/user-attachments/assets/e3d9131f-576e-4c29-a60c-1b827a549546)

I will investigate this issue soon. For now avoid having too much image data in your drawings.

**Comment by jon-dez** [comment]
@0PandaDEV I've implemented a workaround, Here: https://github.com/holxsam/tldraw-in-obsidian/releases/tag/1.5.0

**Comment by 0PandaDEV** [comment]
Thank you i will test this and come back here if the issue was sucessfully resolved.

**Comment by jon-dez** [comment]
@0PandaDEV I just want to let you know that images are no longer stored in base64 when editing drawings that are in .md files. If you have any images that are stored in those .md files you can `ctrl+a` then `ctrl+v` when editing a drawing to move those images from the markdown file into the indexedDB of Obsidian.
