### ISSUE TITLE
Assets override not working when the drawing is embedded

### ISSUE THREAD

**Issue by Hugo-COLLIN** [holxsam/tldraw-in-obsidian#47]
This issue is the continuation of #19 and #44.

My vault is isolated from the internet. So, I downloaded and specified custom fonts and icons to avoid TLdraw loading error and see icons.

It works perfectly in the main editor (thank you @jon-dez for making this possible). But when I try to embed the drawing in a regular note, I get the same error mentioned in #19 : "Could not load assets"

Main editor:
![image](https://github.com/user-attachments/assets/a0ac1de8-5312-443f-9549-a64d7a0a7e3f)

Same drawing but embedded in a note:
![image](https://github.com/user-attachments/assets/69665012-8186-42d8-86ad-07b69662ac65)

Settings:
![image](https://github.com/user-attachments/assets/4fe058c9-0cc8-471c-beaf-454dc5777775)

**Comment by jon-dez** [comment]
Does this occur in interactive mode as well? (Right click embed and toggle interactive mode)

**Comment by Hugo-COLLIN** [comment]
> Does this occur in interactive mode as well? (Right click embed and toggle interactive mode)

@jon-dez No, embed is working in interactive mode:
![image](https://github.com/user-attachments/assets/d3f8f604-00f0-442e-9e55-7c1b311c3448)

**Comment by jon-dez** [comment]
I think I know what is happening. The code that creates the embed preview uses a component provided by the tldraw package ([TldrawImage](https://github.com/tldraw/tldraw/blob/dfd323332ba2ad25e9e8153fbf68b8ffca035cfb/packages/tldraw/src/lib/TldrawImage.tsx#L71)), but that component doesn't allow overrides for static assets. I will file an issue on their repository.

**Comment by jon-dez** [comment]
Ok, I've simulated offline mode by turning off network requests in the dev console. Then I cloned tldraw's repo and made some changes. I created a patch for it so it should work now (at least for me)!
https://github.com/jon-dez/tldraw-in-obsidian/releases/tag/1.5.3

**Comment by jon-dez** [comment]
https://github.com/user-attachments/assets/28c3392e-c697-46e9-9b2a-f44a265cc6c7

**Comment by Hugo-COLLIN** [comment]
@jon-dez Sorry for late response.
I tried v1.7.2 and it's also working for me!
Thank you!

(the double background is a bit disturbing, is there a way to always disable the grey background and/or always disable the dotted background?)
![image](https://github.com/user-attachments/assets/04e49980-54d0-4df8-b74b-98a3dd0b91ca)
