### ISSUE TITLE
Blank page when opening tldraw

### ISSUE THREAD

**Issue by 0PandaDEV** [holxsam/tldraw-in-obsidian#51]
Whenever I open a tldraw file if it's an already existing one or creating a new one I just get a blank black screen instead of the actual canvas.

There is a workaround for this and that is to quit obsidian and then when you start it back up it shows the canvas normally.

Expected:
![CleanShot](https://github.com/user-attachments/assets/405081b7-9438-4bed-892d-dd19617e281b)

Result:
![cleanshot](https://github.com/user-attachments/assets/c8f35204-5925-4b9b-a0d7-eb1e2df613c2)

**Comment by jon-dez** [comment]
@0PandaDEV closing this one due to this being posted twice.
