### ISSUE TITLE
Blank page when opening tldraw

### ISSUE THREAD

**Issue by 0PandaDEV** [holxsam/tldraw-in-obsidian#52]
Whenever I open a tldraw file if it's an already existing one or creating a new one, I just get a blank black screen instead of the actual canvas.

There is a workaround for this and that is to quit obsidian and then when you start it back up it shows the canvas normally.

### Expected:
![CleanShot](https://github.com/user-attachments/assets/405081b7-9438-4bed-892d-dd19617e281b)

### Result:
![cleanshot](https://github.com/user-attachments/assets/c8f35204-5925-4b9b-a0d7-eb1e2df613c2)

**Comment by jon-dez** [comment]
I can't reproduce this, could you install the plugin in a new vault and see if the error occurs?

**Comment by 0PandaDEV** [comment]
Turns out the issue is related to the Self-hosted LiveSync plugin, as soon as I turn it off everything is fine

**Comment by jon-dez** [comment]
Hmm that's weird, I hate to see there being a conflict with another plugin. Even if this doesn't seem to be caused by this plugin at first glance, there may be something this plugin does that breaks functionality. I think this issue should be kept open regardless so it could be tracked.

**Comment by 0PandaDEV** [comment]
Oh, and also the new updated you release that fixed how images are stored is also not compatible with live sync because it's not stored in the vault folder.

**Comment by jon-dez** [comment]
Dang, I think I will need to change how assets are stored. Tldraw does provide API for that though. I will try to find time to implement a workaround for this.

**Comment by jon-dez** [comment]
@0PandaDEV I've released a new version that should now store new images pasted into the drawing as an attachment in your obsidian vault. The only caveat is that any images stored in old drawings aren't extracted into your vault. I will need to implement a feature to extract those images. I've created a new issue for that here #53 
https://github.com/holxsam/tldraw-in-obsidian/releases/tag/1.7.2

**Comment by 0PandaDEV** [comment]
@jon-dez It would be cool to have a option in the settings of tldraw where you can set the folder of the imported images because they are currently just stored in your root vault folder.

**Comment by jon-dez** [comment]
@0PandaDEV The attachments should be stored in your default attachments folder defined in Obsidian setting `Options > Files and links`

**Comment by jon-dez** [comment]
@Mickychen00 Could you create a separate issue and provide more details? Thanks
