### ISSUE TITLE
Failed to load plugin "tldraw"

### ISSUE THREAD

**Issue by gbShaw** [holxsam/tldraw-in-obsidian#54]
Hi! Hope you're doing well!

When I upgraded Tldraw to version 1.7.2, it couldn't be enabled and displayed the message: "Failed to load plugin 'tldraw.'"

The previous version worked fine; I'm not sure what went wrong since I only upgraded all community plugins.

I'm using Obsidian v1.6.7, which is the latest update.

**Comment by gbShaw** [comment]
I have tried different versions, only 1.7.2 and 1.7.1 cannot be loaded.

**Comment by balta2ar** [comment]
I'm experiencing the same with version 1.7.2.

**Comment by gbShaw** [comment]
It is windows11.

And the log, here you are:

```
VM215 plugin:tldraw:95151 TldrawPluginDevelopment.onload: Unloading plugin 'TldrawPlugin'.
app.js:1 Plugin failure: tldraw TypeError: Cannot define property Symbol(Symbol.metadata), object is not extensible
    at defineProperty (<anonymous>)
    at __defNormalProp (plugin:tldraw:16:57)
    at __decoratorMetadata (plugin:tldraw:49:47)
    at __decorateElement (plugin:tldraw:76:15)
    at pluginBuild (plugin:tldraw:94031:30)
    at __decorateElement (plugin:tldraw:71:28)
    at anonymous (plugin:tldraw:94979:16)
    at e.<anonymous> (app.js:1:2292629)
    at app.js:1:237138
    at Object.next (app.js:1:237243)
    at a (app.js:1:235961)
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
s @ app.js:1
Promise.then (async)
l @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
e.enablePlugin @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
a @ app.js:1
Promise.then (async)
l @ app.js:1
a @ app.js:1
Promise.then (async)
l @ app.js:1
a @ app.js:1
Promise.then (async)
l @ app.js:1
a @ app.js:1
Promise.then (async)
l @ app.js:1
a @ app.js:1
Promise.then (async)
l @ app.js:1
a @ app.js:1

```

**Comment by balta2ar** [comment]
Linux here (one on manjaro, one on ubuntu)
```
app.js:1 Plugin failure: tldraw TypeError: Cannot define property Symbol(Symbol.metadata), object is not extensible
    at defineProperty (<anonymous>)
    at __defNormalProp (plugin:tldraw:16:57)
    at __decoratorMetadata (plugin:tldraw:49:47)
    at __decorateElement (plugin:tldraw:76:15)
    at pluginBuild (plugin:tldraw:94031:30)
    at __decorateElement (plugin:tldraw:71:28)
    at anonymous (plugin:tldraw:94979:16)
    at e.<anonymous> (app.js:1:2292629)
    at app.js:1:237138
    at Object.next (app.js:1:237243)
    at a (app.js:1:235961)
```

**Comment by jon-dez** [comment]
Hmm I can't seem to reproduce this, at least on windows 11. I will attempt manjaro or ubuntu if necessary, but I doubt there is a significant difference between the platform that I am using (fedora). I want to assume it is due to a plugin conflict because I am also on Obsidian version 1.6.7.

@gbShaw @balta2ar Can you try to install this plugin in its own vault with no other plugin enabled?

**Comment by balta2ar** [comment]
I confirm that it works when installed in an empty vault, so I started bisecting plugins.

I found at least one conflicting plugin, but maybe there are more:
![image](https://github.com/user-attachments/assets/cf7cd748-9bf8-4baa-8760-3d3b529fa121)

![image](https://github.com/user-attachments/assets/77ebe549-fea4-47f3-a640-ccfa87459575)

**Comment by jon-dez** [comment]
Thanks @balta2ar , I will take a look at this tomorrow (hopefully). I appreciate the time it took for you to find the conflicting plugin.

**Comment by jon-dez** [comment]
Try installing this release using BRAT: https://github.com/jon-dez/tldraw-in-obsidian/releases/tag/1.7.3-bugfix.1

I'm confident this will fix the issue.

**Comment by gbShaw** [comment]
It works well on my platform, thanks!

**Comment by balta2ar** [comment]
Works for me as well, thank you @jon-dez! :heart:
