### ISSUE TITLE
For embedded drawings, add an option to always disable the grey background and/or always disable the dotted background

### ISSUE THREAD

**Issue by Hugo-COLLIN** [holxsam/tldraw-in-obsidian#55]
(Mentioned in #47)
The double background is a bit disturbing, is there a way to always disable the grey background and/or always disable the dotted background?
![image](https://github.com/user-attachments/assets/04e49980-54d0-4df8-b74b-98a3dd0b91ca)

---
@jon-dez workaround for dotted background: https://github.com/holxsam/tldraw-in-obsidian/issues/47#issuecomment-2374656107

**Comment by jon-dez** [comment]
@Hugo-COLLIN https://github.com/holxsam/tldraw-in-obsidian/releases/tag/1.8.1
