### ISSUE TITLE
Provide documentation re: setting custom fonts and icons

### ISSUE THREAD

**Issue by agileadam** [holxsam/tldraw-in-obsidian#58]
Please add to the README some info about setting custom fonts (and icons).

I think I did it correctly:

1. Get a font file. I chose https://github.com/googlefonts/caveat (extracted the .ttf from the zip file)
2. Drop the font file into a folder within Obisidan (I made a structure like this: System/tldraw/Fonts)
3. Open tldraw settings in Obsidian
4. Use the file search button beside the appropriate setting ("Draw (handwriting) font" in my case)
5. Refresh Obsidian?
6. Test

**Comment by jon-dez** [comment]
Yes that is correct. I will try to update the README when I have time.

**Comment by jon-dez** [comment]
I linked to your comment in the README for the guide :sunglasses:, closing this issue
