### ISSUE TITLE
Open Tab In New Window Leads To Error

### ISSUE THREAD

**Issue by tobias0409** [holxsam/tldraw-in-obsidian#60]
Hey,

when I open it in a new window, then the TLDraw Editor crashes.

![grafik](https://github.com/user-attachments/assets/49a8fcff-38c5-4c36-a86b-4b7a88e4af77)

**Comment by jon-dez** [comment]
I've looked into this, and it seems to be a bug on tldraw's part.
https://github.com/tldraw/tldraw/issues/1233

**Comment by jon-dez** [comment]
I'm working on patching the tldraw package to fix this issue, stay tuned!

**Comment by jon-dez** [comment]
@tobias0409 New release on my fork here: https://github.com/jon-dez/tldraw-in-obsidian

You can use BRAT to download this release.

The current features are not working at the moment that I know of
- Fonts are not the same as in the main Obsidian window
- It is not possible to export the file as an svg or png in the pop-out window, you must use the main Obsidian window
