### ISSUE TITLE
Add relative paths

### ISSUE THREAD

**Issue by corysimmons** [holxsam/tldraw-in-obsidian#61]
I don't want to put everything in `/tldraw`

I'd rather have my tldraws colocated with the file I'm using them in. So having something like `{{current_dir}}` placeholder in the folder path would be nice.

**Comment by jon-dez** [comment]
@corysimmons if you run the command "Tldraw: Create a new drawing and embed as attachment" it will create a new tldraw in your preferred attachment folder as configured in your Obsidian settings. Is what you're asking related to something different?

**Comment by corysimmons** [comment]
No that just creates the file at the root of my vault no matter where I use the command.

When you co-locate something it means putting the file next to the file you're working with.

For instance:

```
- Root Vault
  - Some folder
    - Some note
    - My TLDraw diagram <-- it creates it here
  - Some other folder
```

**Comment by jon-dez** [comment]
@corysimmons Understood. Should this be implemented as a separate command, or should this be something that overrides the default behavior when creating a new tldraw file? If it should override the default behavior, then a new settings option to toggle this behavior will be made available. Perhaps both options?

**Comment by jon-dez** [comment]
Got it, I'll post on this thread when I have a preview version built and installable through BRAT

**Comment by jon-dez** [comment]
@corysimmons https://github.com/jon-dez/tldraw-in-obsidian/releases/tag/1.11.0

**Comment by corysimmons** [comment]
Looks good. Can you ping me when 1.11 is available and I'll test it out?

**Comment by jon-dez** [comment]
You should be able to download it by installing it through the BRAT plugin, which can be installed in the community plugins section in Obsidian and providing a link to my repository. Would you like me to create a release for it in this repository?

**Comment by corysimmons** [comment]
I added it with BRAT and it's still 1.9?

![image](https://github.com/user-attachments/assets/c6ec82bb-419c-4dc1-8707-bc08f5c73b9e)

**Comment by jon-dez** [comment]
Does your "Beta Plugin List" section in the BRAT settings show this?

![image](https://github.com/user-attachments/assets/328c6b25-2c68-411b-b830-4aea47730446)

If not add https://github.com/jon-dez/tldraw-in-obsidian

**Comment by corysimmons** [comment]
Yes 
![image](https://github.com/user-attachments/assets/35b69b75-5be7-4332-a889-a8acc50d019b)

**Comment by corysimmons** [comment]
@jon-dez This is perfect. Thank you! The only thing I would suggest is allowing someone to add a folder to it so I can do something like `Colocated Folder/TLDraws/`

**Comment by jon-dez** [comment]
Done: https://github.com/jon-dez/tldraw-in-obsidian/releases/tag/1.12.0

**Comment by corysimmons** [comment]
Did that get built/released correctly?

![image](https://github.com/user-attachments/assets/60a0e2a4-1e47-4442-b22c-dd8ea3c33f8a)

![image](https://github.com/user-attachments/assets/b925118b-a80f-470c-831d-a27bc7f43a71)

I don't get the subfolder like in your release notes.

**Comment by jon-dez** [comment]
You might need to reload Obsidian

**Comment by corysimmons** [comment]
Works perfect! Thank you!
