### ISSUE TITLE
Add padding when embedding

### ISSUE THREAD

**Issue by Igorgro** [holxsam/tldraw-in-obsidian#65]
When embedding tldraw drawing into a note the content is cut off too closer to drawing content. It worth adding a small (or configurable) padding around drawing content. For example on the following picture (this is a screenshot of tldraw drawing embedded into a note) the top part of the arrow is cut off:
![image](https://github.com/user-attachments/assets/0d50b49d-e703-435b-8466-1c465cdf77f8)

**Comment by jon-dez** [comment]
I can implement this as a configurable option in the settings tab. Though, I think having a padding that applies to all embed might not be the best approach. There is a way to set the bounds manually for an individual embed, though it might be a little tedious (https://github.com/holxsam/tldraw-in-obsidian/issues/59: See "Set bounds on embed"). I can try to implement a better way to set the bounds automatically by using a rectangle select tool in the interactive mode. What do you think?

**Comment by jon-dez** [comment]
@Igorgro Check out this release: https://github.com/jon-dez/tldraw-in-obsidian/releases/tag/1.14.0

You can set custom padding via the settings panel, or control the bounds of the embed view by using the embed bounds selection tool.

**Comment by Igorgro** [comment]
I tried the new setting and it does exactly what I want, thanks!

**Comment by Igorgro** [comment]
The only problem I see now is the huge padding after embedded picture. It seems unrelated to this feature, should I create a new issue for that?

![image](https://github.com/user-attachments/assets/da5a46b6-5164-40ef-822e-394928e5cb20)

**Comment by jon-dez** [comment]
Yes, if you don't mind creating a new issue
