### ISSUE TITLE
New drawing confirmation modal not loading suggestions correctly

### ISSUE THREAD

**Issue by oliveryh** [holxsam/tldraw-in-obsidian#67]
**Steps to Reproduce**
- Enable the plugin in a fresh install of Obsidian (or one where there are no settings persisting from past installations of this plugin)
- Create a new drawing (.tldr), then open in a New Tab

**I expect**
- To have a suggestion modal I can interact with, to eventually create a new drawing

**Instead I see**
- The modal doesn't allow any interaction other than to close the window
![image](https://github.com/user-attachments/assets/2eec979a-f35c-469a-9db7-fe8f30ff7a41)

- There is an error in the console
```
plugin:tldraw:98895 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'folder')
    at _NewTldrawFileConfirmationModal.renderSuggestion (plugin:tldraw:98895:122)
    at e.setSuggestions (app.js:1:1432923)
    at i (app.js:1:1760219)
    at _NewTldrawFileConfirmationModal.<anonymous> (app.js:1:1760403)
    at app.js:1:237228
    at Object.next (app.js:1:237333)
    at a (app.js:1:236051)
```

**More Information**

I'm using
- Obsidian on MacOS v1.7.5
- Plugin v1.12.0

When loading up the settings, I can see that the File Destination Method is unset, despite this not being an option. 
![image](https://github.com/user-attachments/assets/0fc1727a-4abd-4584-bc9a-a2fa9dcbcab3)

If I set this to use my default, and set that up correctly, the issue with the modal goes.

The issue appears to be partly due to the `getSuggestions` function returning a suggestion with `folder: undefined`.

**Comment by jon-dez** [comment]
Just fixed in this released: https://github.com/jon-dez/tldraw-in-obsidian/releases/tag/1.14.1

**Comment by oliveryh** [comment]
Thanks. I've tested v1.14.1 without a `data.json` present in the plugin directory and it appears to fix the issue of the modal not working. Feel free to close if/when you want.

**Comment by jon-dez** [comment]
No problem, and thanks for testing the release!
