### ISSUE TITLE
Padding after embedded image

### ISSUE THREAD

**Issue by Igorgro** [holxsam/tldraw-in-obsidian#68]
When embedding tldraw image into the note, there is a huge padding below it
![image](https://github.com/user-attachments/assets/da5a46b6-5164-40ef-822e-394928e5cb20)

There is no additional attributes, except size (because otherwise it fills the whole width)
![image](https://github.com/user-attachments/assets/d2b4cfb2-9f14-47aa-bf22-379b03b27810)

**Comment by jon-dez** [comment]
I've created a new release: https://github.com/jon-dez/tldraw-in-obsidian/releases/tag/1.16.0

Could you test it and let me know if this works for you?

**Comment by Igorgro** [comment]
Yes, it works, but image is now centered. Is it intentionally?
![image](https://github.com/user-attachments/assets/48783089-7137-4ad3-b89d-1a259410fe34)

**Comment by jon-dez** [comment]
Yes, this is intentional
