### ISSUE TITLE
Incompatible schema. Unable to load file

### ISSUE THREAD

**Issue by fmusayev** [holxsam/tldraw-in-obsidian#69]
Hi, 

Recently, I’ve encountered an issue with loading newly saved files from the official tldraw website. I suspect this might be due to recent schema changes in tldraw.

Older files load without any problems, and I can still create and save new projects. However, any files exported from website fail to load properly.

I’ve attached a screenshot of the console for reference.

Let me know if you’d like further tweaks!

<img width="1794" alt="Screenshot 2024-11-18 at 03 12 49" src="https://github.com/user-attachments/assets/c5507256-baa7-4c30-a104-eece25719ac9">

**Comment by jon-dez** [comment]
Hello, could you test the following release:

https://github.com/jon-dez/tldraw-in-obsidian/releases/tag/1.15.0

I updated the tldraw package to version 3.4.1
