### ISSUE TITLE
Embed shows souce json code

### ISSUE THREAD

**Issue by kevinhojae** [holxsam/tldraw-in-obsidian#7]
If I embed tldraw file on the note, it shows raw json source, not the tldraw canvas. Is there any way to show embeded canvas like excalidraw?

> tldraw embed

![CleanShot 2023-11-17 at 16 03 48@2x](https://github.com/holxsam/tldraw-in-obsidian/assets/87641554/40edbfa3-d083-4cdf-aca9-664f57dde778)

> excalidraw embed

![CleanShot 2023-11-17 at 16 05 18@2x](https://github.com/holxsam/tldraw-in-obsidian/assets/87641554/cb6c48b4-6645-4136-b60d-5c91604e51d9)

**Comment by holxsam** [comment]
There is not a way to show the canvas as an embed yet. I've been a bit busy so I haven't been able to work on plugin but it's at the top of my list feature wise.

**Comment by jhoogeboom** [comment]
Perhaps this is useful: https://github.com/kitschpatrol/tldraw-cli?tab=readme-ov-file#api-usage

**Comment by jon-dez** [comment]
@kevinhojae 

I've made a pull request that implements, this feature. See more info here https://github.com/holxsam/tldraw-in-obsidian/pull/22#issuecomment-2154213634

**Comment by holxsam** [comment]
Merged jon's PR and released the update: https://github.com/holxsam/tldraw-in-obsidian/releases/tag/1.0.6
