### ISSUE TITLE
When dragged in a canvas, drawing does not render and instead raw JSON is displayed

### ISSUE THREAD

**Issue by nileshtrivedi** [holxsam/tldraw-in-obsidian#70]
Here is a comparison of excalidraw image rendering correctly within canvas, but tldraw shows the raw JSON code instead:

![image](https://github.com/user-attachments/assets/502ba5c9-c0af-4709-8d26-56643d4e90fd)

**Comment by jon-dez** [comment]
I've created a new release: https://github.com/jon-dez/tldraw-in-obsidian/releases/tag/1.16.0

Could you test it and let me know if this works for you?

**Comment by nileshtrivedi** [comment]
@jon-dez Thanks. I installed 1.16.0 from your repo (via BRAT) and it works.
![image](https://github.com/user-attachments/assets/8666fcaf-876e-4126-bde6-025d836eeef0)
