### ISSUE TITLE
Drawing lag when there are many existing objects

### ISSUE THREAD

**Issue by thanhnguyen2187** [holxsam/tldraw-in-obsidian#74]
Hi!

Really appreciate the awesome plugin!!

The only gripe I have is that when there are many existing objects/strokes, new lines gets noticeably laggy. The issue only happens with the plugin version, not the online version on tldraw.com, and I was wondering if we can do anything about it.

Related issue: https://github.com/tldraw/tldraw/issues/1247

Thanks!

**Comment by jon-dez** [comment]
@thanhnguyen2187 Could you try the latest release?

**Comment by thanhnguyen2187** [comment]
Thanks!! I noticed that the lag also improved when I upgrade my OS (was using NixOS 24.05 and switched to NixOS 24.11). Maybe `libinput` also has something to do with it? Either way, it's way better now. Really appreciate your work!!

**Comment by jon-dez** [comment]
No problem, thanks!
