### ISSUE TITLE
Add page into embed options

### ISSUE THREAD

**Issue by bernatesquirol** [holxsam/tldraw-in-obsidian#75]
Would be great to have also `page` additionally to `size, pos, showBg` as an alt_text option.
But i don't know how can we know or copy page_id from tldraw.
https://github.com/holxsam/tldraw-in-obsidian/issues/59

**Comment by jon-dez** [comment]
Working on this specific feature. Stay tuned

**Comment by jon-dez** [comment]
@bernatesquirol Check the latest release :sunglasses:

**Comment by Maksim3l** [comment]
But how is this used?
